# Generated by Django 5.1.7 on 2025-03-16 20:26

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('action_type', models.CharField(choices=[('document_requested', 'Document Requested')], max_length=50)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('action_type',), name='action_type_unique')],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('condition_type', models.CharField(choices=[('is_business_owner', 'Is Business Owner'), ('is_returning', 'Is Returning'), ('filed_us_taxes', 'Filed US Taxes')], max_length=50)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('condition_type',), name='condition_type_unique')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('action_type', models.CharField(choices=[('document_requested', 'Document Requested')], max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical action',
                'verbose_name_plural': 'historical actions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCondition',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('condition_type', models.CharField(choices=[('is_business_owner', 'Is Business Owner'), ('is_returning', 'Is Returning'), ('filed_us_taxes', 'Filed US Taxes')], max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical condition',
                'verbose_name_plural': 'historical conditions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTrigger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('trigger_type', models.CharField(choices=[('application_submission', 'Application Submission')], max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical trigger',
                'verbose_name_plural': 'historical triggers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('enabled', models.BooleanField(default=True)),
                ('actions', models.ManyToManyField(related_name='rules', to='rules.action')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalRuleRun',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('completed', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school_application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.schoolapplication')),
                ('rule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rules.rule')),
            ],
            options={
                'verbose_name': 'historical rule run',
                'verbose_name_plural': 'historical rule runs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRuleCondition',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('conjunction', models.CharField(choices=[('and', 'And'), ('or', 'Or')], max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('condition', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rules.condition')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rules.rule')),
            ],
            options={
                'verbose_name': 'historical rule condition',
                'verbose_name_plural': 'historical rule conditions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('conjunction', models.CharField(choices=[('and', 'And'), ('or', 'Or')], max_length=50)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_conditions', to='rules.condition')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_conditions', to='rules.rule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='conditions',
            field=models.ManyToManyField(related_name='rules', through='rules.RuleCondition', to='rules.condition'),
        ),
        migrations.CreateModel(
            name='RuleRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('completed', models.BooleanField(default=False)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_runs', to='rules.rule')),
                ('school_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_runs', to='applications.schoolapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('trigger_type', models.CharField(choices=[('application_submission', 'Application Submission')], max_length=50)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trigger_type',), name='trigger_type_unique')],
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='rules.trigger'),
        ),
        migrations.CreateModel(
            name='HistoricalRule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('enabled', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trigger', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rules.trigger')),
            ],
            options={
                'verbose_name': 'historical rule',
                'verbose_name_plural': 'historical rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
