# Generated by Django 5.1.7 on 2025-03-16 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='requested_document_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('W2', 'W2'), ('pay_stub', 'Pay Stub'), ('business_tax_document', 'Business Tax Document'), ('bank_statement', 'Bank Statement')], max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalaction',
            name='requested_document_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('W2', 'W2'), ('pay_stub', 'Pay Stub'), ('business_tax_document', 'Business Tax Document'), ('bank_statement', 'Bank Statement')], max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action_type', 'document_requested'), ('requested_document_types__isnull', False)), models.Q(('action_type', 'document_requested'), _negated=True), _connector='OR'), name='requested_document_types_required_for_document_requested'),
        ),
    ]
