# Generated by Django 5.1.7 on 2025-03-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_action_requested_document_types_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='action',
            name='action_type_unique',
        ),
    ]
