# Generated by Django 5.1.7 on 2025-03-16 20:26

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('document_type', models.CharField(choices=[('W2', 'W2'), ('pay_stub', 'Pay Stub'), ('business_tax_document', 'Business Tax Document'), ('bank_statement', 'Bank Statement')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Datetime Created')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('file', models.TextField(blank=True, max_length=100, null=True)),
                ('document_type', models.CharField(choices=[('W2', 'W2'), ('pay_stub', 'Pay Stub'), ('business_tax_document', 'Business Tax Document'), ('bank_statement', 'Bank Statement')], max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document',
                'verbose_name_plural': 'historical documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
