# Generated by Django 5.1.7 on 2025-03-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_email_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='last_email_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
